list: $/mesb/workflow/models/module/columns.yaml
modelClass: Mesb\Workflow\Models\Module
title: Module
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mesb/workflow/module/update/:id'
