list: $/mesb/workflow/models/status/columns.yaml
modelClass: Mesb\Workflow\Models\Status
title: Status
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mesb/workflow/status/update/:id'
