list: $/mesb/workflow/models/statusto/columns.yaml
modelClass: Mesb\Workflow\Models\StatusTo
title: StatusTo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mesb/workflow/statusto/update/:id'
